import type { IncomingMessage, ServerResponse } from "node:http";

export default function handler(_req: IncomingMessage, res: ServerResponse) {
  res.statusCode = 200;
  res.setHeader("content-type", "text/html; charset=utf-8");
  res.end(`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Figranium MCP</title><style>
*{box-sizing:border-box}body{margin:0;background:#f4f9fc;color:#171b27;font-family:Arial,sans-serif}.shell{min-height:100vh;padding:24px 32px}.nav{height:108px;border:1px solid #d8e0e5;border-radius:28px;background:#fff;box-shadow:0 2px 5px #10182812;display:flex;align-items:center;padding:0 42px;gap:44px}.brand{font-size:30px;color:#111;text-decoration:none}.links{display:flex;gap:40px;margin:auto}.links a{color:#4d5868;text-decoration:none}.github{border:1px solid #d3dce3;border-radius:14px;padding:14px 18px;text-decoration:none;color:#242a35}.hero{max-width:1440px;margin:auto;min-height:690px;display:grid;grid-template-columns:1.08fr .92fr;align-items:center;gap:72px;padding:70px 34px}.eyebrow{color:#2878ed;font-size:17px;margin-bottom:20px}.hero h1{font-size:67px;line-height:1.08;letter-spacing:-2.8px;font-weight:400;margin:0 0 24px}.hero p{font-size:22px;line-height:1.5;color:#657080;max-width:700px}.actions{display:flex;gap:16px;margin-top:32px}.button{padding:17px 24px;border-radius:10px;text-decoration:none}.primary{background:#2878ed;color:#fff}.secondary{background:#eaf0f5;color:#293241}.visual{position:relative;height:450px}.card{position:absolute;background:#fff;border:2px solid #202a3b;border-radius:12px;box-shadow:0 16px 40px #2878ed18;padding:20px;width:150px;height:115px}.one{left:10%;top:7%;transform:rotate(7deg)}.two{right:9%;top:16%;transform:rotate(-5deg)}.three{left:30%;bottom:8%;transform:rotate(-8deg)}.line{position:absolute;left:20%;top:28%;width:63%;height:48%;border:3px solid #111;border-left-color:transparent;border-bottom-color:transparent;border-radius:50%;transform:rotate(20deg)}.dot{position:absolute;width:32px;height:32px;border-radius:50%;background:#2878ed;left:57%;top:47%}.mini{height:8px;border-radius:8px;background:#2878ed;margin:9px 0}.gray{background:#d7dde2;width:70%}@media(max-width:850px){.links{display:none}.hero{grid-template-columns:1fr}.hero h1{font-size:48px}.visual{display:none}.shell{padding:14px}}
</style></head><body><div class="shell"><nav class="nav"><a class="brand" href="https://figranium.dev">✣ figranium</a><div class="links"><a href="https://figranium.dev/docs">Docs</a><a href="https://figranium.dev/blog">Blog</a><a href="https://figranium.dev/integrations">Integrations</a><a href="https://figranium.dev/templates">Templates</a></div><a class="github" href="https://github.com/figranium/figranium-mcp">GitHub</a></nav><main class="hero"><section><div class="eyebrow">Figranium MCP</div><h1>Give your AI a browser it can actually use.</h1><p>Connect ChatGPT, Claude, Cursor, or any MCP client to Figranium. Create tasks, run them, manage schedules, and turn websites into reusable workflows from your AI client.</p><div class="actions"><a class="button primary" href="https://figranium.dev/docs">Connect Figranium</a><a class="button secondary" href="https://github.com/figranium/figranium-mcp">View on GitHub</a></div></section><div class="visual"><div class="line"></div><div class="dot"></div><div class="card one"><div class="mini"></div><div class="mini gray"></div></div><div class="card two"><div class="mini gray"></div><div class="mini"></div></div><div class="card three"><div class="mini"></div><div class="mini gray"></div></div></div></main></div></body></html>`);
}
